import React from 'react';
import { Typography, Box } from '@mui/material';

const TrafficMap = () => (
  <Box>
    <Typography variant="h6">Real-Time Traffic Optimization</Typography>
    <Typography>Dynamic routes generated by AI drone surveillance.</Typography>
  </Box>
);

export default TrafficMap;